### ISSUE TITLE
get_token has weird behavior

### ISSUE THREAD

**Issue by antoine-lizee** [UCSF-MSLAB/msbwaiter#3]
1. What is the purpose of the argument `token_name`? 
2. What is a use case of searching in the workspace instead of only allowing use of environment variable?

**Comment by antoine-lizee** [comment]
I actually like the (1.) for 2 reasons: easy to see the default + potential use of get_token with different keys, e.g. for production and uat. It's a very small use-case (vs just changing the token) but it might be useful.

I still don't like the (2.) because the risk of collision/deletion is big.

**Comment by alisha-agrawal** [comment]
The reason for (2.) is to allow the user to set msbwaiter_token at the beginning of a script. This will let the script to run automatically instead of prompting the user to enter their token each time you run the script/call library(msbwaiter).

**Comment by alisha-agrawal** [comment]
actually, the user could just set an environment variable instead of a workspace variable at the beginning of a script right?

**Comment by antoine-lizee** [comment]
Should be solved by #5
